#!/usr/bin/env python3
"""Build every graphic and rewrite README.md from config.json.

    python scripts/generate.py --demo    # no token, synthetic stats
    python scripts/generate.py           # uses GITHUB_TOKEN / PROFILE_TOKEN

Writes only files whose bytes actually changed, so the scheduled workflow
produces a commit only when something moved.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import asciikit
import github_api
import graphs
import headings

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECTIONS = ["about", "stack", "projects", "stats", "colophon"]

COLOPHON = """Every graphic on this page is generated by this repository, not embedded from
anyone else's server. `wordmark.svg` is text pushed through a character ramp;
the calendar and the section headings are drawn [by a scheduled action](.github/workflows/profile.yml)
straight from the GitHub GraphQL API, once a day, committing only what changed.

They animate with SMIL inside the SVG, because GitHub strips scripts from
READMEs — and since nothing loads from a third party, nothing here can
rate-limit or go dark. The headings are images for the same reason: GitHub also
strips CSS, so an image is the only way to set them in this page's typeface.

The typeface is [JetBrains Mono](scripts/fonts), subset to just the characters
each graphic draws and inlined as base64. That is not only for looks — the
wordmark's grid assumes an advance width of exactly 0.600 em, and a viewer whose
default monospace is narrower would otherwise see it squeezed."""


def write_if_changed(path: str, content: str) -> bool:
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    new = content.encode("utf-8")
    if os.path.exists(full):
        with open(full, "rb") as fh:
            if fh.read() == new:
                return False
    with open(full, "wb") as fh:
        fh.write(new)
    print(f"  wrote {path}")
    return True


def build_readme(cfg: dict) -> str:
    out = ["![](wordmark.svg)", ""]

    links = " · ".join(f"[{l['label']}]({l['url']})" for l in cfg["links"])
    out += [links, ""]

    out += ["![](hd-about.svg)"]
    for line in cfg["about"]["quote"]:
        out.append(f"> {line}")
    out.append("")
    out += cfg["about"]["body"]
    out.append("")

    out += ["![](hd-stack.svg)", "", f"`{cfg['stack']}`", ""]

    out += ["![](hd-projects.svg)", ""]
    for proj in cfg["projects"]:
        title = f"[{proj['name']}]({proj['url']})" if proj.get("url") else proj["name"]
        badge = " `private`" if proj.get("private") else ""
        out.append(f"**{title}**{badge} · `{proj['tags']}`  ")
        out.append("  \n".join(proj["description"]))
        out.append("")

    stats = cfg.get("stats", {})
    if any(stats.get(k) for k in ("year", "streak", "languages")):
        out += ["![](hd-stats.svg)", ""]
        if stats.get("streak"):
            out += ["![](streak.svg)", ""]
        if stats.get("year"):
            out += ["![](year.svg)", ""]
        if stats.get("languages"):
            out += ["![](langs.svg)", ""]

    out += ["![](hd-colophon.svg)", "", COLOPHON, ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--demo", action="store_true",
                        help="synthetic stats, no network")
    args = parser.parse_args()

    with open(os.path.join(ROOT, "config.json")) as fh:
        cfg = json.load(fh)

    changed = 0

    print("wordmark")
    changed += write_if_changed("wordmark.svg", asciikit.wordmark(cfg["wordmark"]))

    print("headings")
    for name in SECTIONS:
        changed += write_if_changed(f"hd-{name}.svg", headings.heading(name))

    if args.demo:
        days = github_api.demo_days()
        langs = github_api.demo_languages()
    else:
        token = github_api.token_from_env()
        if not token:
            print("no GITHUB_TOKEN / PROFILE_TOKEN set; re-run with --demo",
                  file=sys.stderr)
            return 1
        days = github_api.fetch_days(cfg["login"], token)
        langs = github_api.fetch_languages(cfg["login"], token)

    current, longest, total = github_api.streaks(days)
    print(f"stats: {total} contributions, {current} current, {longest} longest")

    changed += write_if_changed("year.svg", graphs.year_calendar(days))
    changed += write_if_changed("streak.svg",
                                graphs.streak_card(current, longest, total))
    if langs:
        changed += write_if_changed("langs.svg", graphs.language_bar(langs))

    print("readme")
    changed += write_if_changed("README.md", build_readme(cfg))

    print(f"{changed} file(s) changed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
